In [9]:
#Numpy Documentation:  https://docs.python.org/3/library/
#Tutorials:  https://www.tutorialspoint.com/numpy/,  https://docs.scipy.org/doc/numpy/user/quickstart.html
#Library Purpose: Numerical Python (NumPy) is the fundamental package for scientific computing with Python
#Includes: powerful N-dimensional array object,  useful linear algebra, Fourier transform, and random number capabilities
#Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 
#Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

import numpy as np
#random num gen classes
from numpy.random import rand
#Linear algebra classes
from numpy.linalg import solve, inv

In [10]:
#overview of numpy data structures & operations
def data_struct():
    print("Array creation - does not exist in python base libraries")
    x = np.array([1, 2, 3])
    print(x)  #prints array([1, 2, 3])
    y = np.arange(10)  # like Python's range, but returns an array
    print(y) #prints array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

    print("Basic Numpy operations")
    a = np.array([1, 2, 3, 6])
    b = np.linspace(0, 2, 4)  # create an array with four equally spaced points starting with 0 and ending with 2.
    print(b)  #Prints 
    c = a - b #Array/set Difference
    print(c) # rints array([ 1.        ,  1.33333333,  1.66666667,  4.        ])
    a**2 #All elements ^2
    print(a) #prints array([1 2 3 6])

    print("Universal numpy functions")
    a = np.linspace(-np.pi, np.pi, 100)  
    b = np.sin(a) #sine function
    c = np.cos(a) #cosine function

    a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
    print("Transpose array - from linalg class")
    a.transpose()  
    '''array([[ 1. ,  3. ,  5. ],
       [ 2. ,  4. ,  9. ],
       [ 3. ,  6.7,  5. ]]) '''
    inv(a)
    ''' array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]]) '''
    b =  np.array([3, 2, 1])
    print("solve the equation ax = b")
    solve(a, b) 
    #prints results - x = array([-4.83050847,  2.13559322,  1.18644068])
    c = rand(3, 3) * 20  # create a 3x3 random matrix of values within [0,1] scaled by 20
    print(c)
    ''' ex. array([[  3.98732789,   2.47702609,   4.71167924],
       [  9.24410671,   5.5240412 ,  10.6468792 ],
       [ 10.38136661,   8.44968437,  15.17639591]]) '''
    print("matrix multiplication")
    np.dot(a, c)  
    ''' ex. array([[  53.61964114,   38.8741616 ,   71.53462537],
       [ 118.4935668 ,   86.14012835,  158.40440712],
       [ 155.04043289,  104.3499231 ,  195.26228855]]) '''
    a @ c # Starting with Python 3.5 and NumPy 1.10
    ''' ex. array([[  53.61964114,   38.8741616 ,   71.53462537],
       [ 118.4935668 ,   86.14012835,  158.40440712],
       [ 155.04043289,  104.3499231 ,  195.26228855]]) '''


In [11]:
data_struct()  

Array creation - does not exist in python base libraries
[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
Basic Numpy operations
[0.         0.66666667 1.33333333 2.        ]
[1.         1.33333333 1.66666667 4.        ]
[1 2 3 6]
Universal numpy functions
Transpose array - from linalg class
solve the equation ax = b
[[12.5236598   1.02335622 19.03375777]
 [17.96250484  7.29206062 15.78733617]
 [17.16149418  6.29748448  3.21196677]]
matrix multiplication


In [17]:
def data_types():
    print("find data type of variable")
    dt = np.dtype(np.int32) 
    print(dt)  #prints int32

    a = np.array([(10,),(20,),(30,)], dtype = dt) 
    print(a)  #prints [(10,) (20,) (30,)]
    
    #ndarray example - mixed types
    student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
    a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
    print(a)  #prints [('abc', 21, 50.0), ('xyz', 18, 75.0)]
    print(a['age']) #prints [(10 20 30]

In [18]:
data_types()  

find data type of variable
int32
[[10]
 [20]
 [30]]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[21 18]


In [14]:
#copy existing data structure into new array
# convert list to ndarray 
import numpy as np 

# convert list to ndarray 
x = [1,2,3] #python list
a = np.asarray(x) #into numpy array
print(a)

# ndarray from tuple 
x = (1,2,3) 
a = np.asarray(x) 
print(a)

# ndarray from list of tuples 
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

[1 2 3]
[1 2 3]
[(1, 2, 3) (4, 5)]


In [15]:
import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print('Our array is:' )
print(a)  
print('\n'  )

print('Applying amin() function:' )
print(np.amin(a,1) )
print('\n'  )

print('Applying amin() function again:' )
print(np.amin(a,0) )
print('\n'  )

print('Applying amax() function:' )
print(np.amax(a) )
print('\n'  )

print('Applying amax() function again:' )
print(np.amax(a, axis = 0))


#numpy.ptp() function returns the range (maximum-minimum) of values along an axis.
print('Applying ptp() function:' )
print(np.ptp(a) )
print('\n'  )

print('Applying ptp() function along axis 1:' )
print(np.ptp(a, axis = 1) )
print('\n'   )

print('Applying ptp() function along axis 0:')
print(np.ptp(a, axis = 0) )

print('Applying percentile() function:' )
print(np.percentile(a,50) )
print('\n'  )

print('Applying percentile() function along axis 1:') 
print(np.percentile(a,50, axis = 1) )
print('\n'  )

print('Applying percentile() function along axis 0:')
print(np.percentile(a,50, axis = 0))

print('Applying median() function:' )
print( np.median(a) )
print( '\n'  )

print( 'Applying median() function along axis 0:') 
print( np.median(a, axis = 0) )
print( '\n'  )
 
print( 'Applying median() function along axis 1:' )
print( np.median(a, axis = 1))

print( 'Applying mean() function:' )
print( np.mean(a) )
print( '\n'  )

print( 'Applying mean() function along axis 0:' )
print( np.mean(a, axis = 0) )
print( '\n'  )

print( 'Applying mean() function along axis 1:' )
print( np.mean(a, axis = 1))
   
      


Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying amin() function:
[30 10 50]


Applying amin() function again:
[30 20 10]


Applying amax() function:
90


Applying amax() function again:
[80 90 70]
Applying ptp() function:
80


Applying ptp() function along axis 1:
[40 70 40]


Applying ptp() function along axis 0:
[50 70 60]
Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]
Applying median() function:
50.0


Applying median() function along axis 0:
[50. 40. 60.]


Applying median() function along axis 1:
[40. 20. 60.]
Applying mean() function:
50.0


Applying mean() function along axis 0:
[53.33333333 50.         46.66666667]


Applying mean() function along axis 1:
[46.66666667 36.66666667 66.66666667]


In [16]:
#reshape and modify array
a = np.arange(6).reshape(3,2) 

print('Our array is:') 
print(a) 
print('\n')  

print('Modified array:')
wt = np.array([3,5]) 
print(np.average(a, axis = 1, weights = wt) 
print('\n')  

print 'Modified array:' 
print np.average(a, axis = 1, weights = wt, returned = True)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Our array is:')? (<ipython-input-16-720ffed1c6e4>, line 4)